# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Patristic <- function(mcmc_samples, log_patristic_distances, x_pair, x_ind, z, spatial_dists, v, metrop_var_phi_trans, a_sigma2_epsilon_prior = NULL, b_sigma2_epsilon_prior = NULL, sigma2_regress_prior = NULL, a_sigma2_zeta_prior = NULL, b_sigma2_zeta_prior = NULL, a_tau2_prior = NULL, b_tau2_prior = NULL, a_phi_prior = NULL, b_phi_prior = NULL, sigma2_epsilon_init = NULL, beta_init = NULL, gamma_init = NULL, theta_init = NULL, sigma2_zeta_init = NULL, eta_init = NULL, tau2_init = NULL, phi_init = NULL) {
    .Call(`_GenePair_Patristic`, mcmc_samples, log_patristic_distances, x_pair, x_ind, z, spatial_dists, v, metrop_var_phi_trans, a_sigma2_epsilon_prior, b_sigma2_epsilon_prior, sigma2_regress_prior, a_sigma2_zeta_prior, b_sigma2_zeta_prior, a_tau2_prior, b_tau2_prior, a_phi_prior, b_phi_prior, sigma2_epsilon_init, beta_init, gamma_init, theta_init, sigma2_zeta_init, eta_init, tau2_init, phi_init)
}

delta_update <- function(y, xtx, x_trans, z, p_x, p_d, x_prior, sigma2_epsilon, theta_old) {
    .Call(`_GenePair_delta_update`, y, xtx, x_trans, z, p_x, p_d, x_prior, sigma2_epsilon, theta_old)
}

eta_update <- function(vtv, v_trans, m, theta, sigma2_zeta, tau2_old, corr_inv) {
    .Call(`_GenePair_eta_update`, vtv, v_trans, m, theta, sigma2_zeta, tau2_old, corr_inv)
}

neg_two_loglike_update <- function(y, x_pair, x_ind, z, n_star, sigma2_epsilon, beta, gamma, theta) {
    .Call(`_GenePair_neg_two_loglike_update`, y, x_pair, x_ind, z, n_star, sigma2_epsilon, beta, gamma, theta)
}

phi_update <- function(spatial_dists, m, a_phi, b_phi, spatial_corr_info, eta, tau2, phi_old, metrop_var_phi_trans, acctot_phi_trans) {
    .Call(`_GenePair_phi_update`, spatial_dists, m, a_phi, b_phi, spatial_corr_info, eta, tau2, phi_old, metrop_var_phi_trans, acctot_phi_trans)
}

rcpparma_hello_world <- function() {
    .Call(`_GenePair_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_GenePair_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_GenePair_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_GenePair_rcpparma_bothproducts`, x)
}

sigma2_epsilon_update <- function(y, x_pair, x_ind, z, n_star, a_sigma2_epsilon, b_sigma2_epsilon, beta_old, gamma_old, theta_old) {
    .Call(`_GenePair_sigma2_epsilon_update`, y, x_pair, x_ind, z, n_star, a_sigma2_epsilon, b_sigma2_epsilon, beta_old, gamma_old, theta_old)
}

sigma2_zeta_update <- function(v, n, a_sigma2_zeta, b_sigma2_zeta, theta, eta_old) {
    .Call(`_GenePair_sigma2_zeta_update`, v, n, a_sigma2_zeta, b_sigma2_zeta, theta, eta_old)
}

spatial_corr_fun <- function(m, spatial_dists, phi) {
    .Call(`_GenePair_spatial_corr_fun`, m, spatial_dists, phi)
}

tau2_update <- function(m, a_tau2, b_tau2, eta, corr_inv) {
    .Call(`_GenePair_tau2_update`, m, a_tau2, b_tau2, eta, corr_inv)
}

theta_update <- function(y, x_pair, x_ind, ztz, z_trans, v, n, sigma2_epsilon, beta, gamma, sigma2_zeta_old, eta_old) {
    .Call(`_GenePair_theta_update`, y, x_pair, x_ind, ztz, z_trans, v, n, sigma2_epsilon, beta, gamma, sigma2_zeta_old, eta_old)
}

