# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Clustered <- function(mcmc_samples, clustered_indicators, x_pair, x_ind, z, spatial_dists, v, metrop_var_phi_trans, sigma2_regress_prior = NULL, a_sigma2_zeta_prior = NULL, b_sigma2_zeta_prior = NULL, a_tau2_prior = NULL, b_tau2_prior = NULL, a_phi_prior = NULL, b_phi_prior = NULL, beta_init = NULL, gamma_init = NULL, theta_init = NULL, sigma2_zeta_init = NULL, eta_init = NULL, tau2_init = NULL, phi_init = NULL) {
    .Call(`_GenePair_Clustered`, mcmc_samples, clustered_indicators, x_pair, x_ind, z, spatial_dists, v, metrop_var_phi_trans, sigma2_regress_prior, a_sigma2_zeta_prior, b_sigma2_zeta_prior, a_tau2_prior, b_tau2_prior, a_phi_prior, b_phi_prior, beta_init, gamma_init, theta_init, sigma2_zeta_init, eta_init, tau2_init, phi_init)
}

Patristic <- function(mcmc_samples, log_patristic_distances, x_pair, x_ind, z, spatial_dists, v, metrop_var_phi_trans, a_sigma2_epsilon_prior = NULL, b_sigma2_epsilon_prior = NULL, sigma2_regress_prior = NULL, a_sigma2_zeta_prior = NULL, b_sigma2_zeta_prior = NULL, a_tau2_prior = NULL, b_tau2_prior = NULL, a_phi_prior = NULL, b_phi_prior = NULL, sigma2_epsilon_init = NULL, beta_init = NULL, gamma_init = NULL, theta_init = NULL, sigma2_zeta_init = NULL, eta_init = NULL, tau2_init = NULL, phi_init = NULL) {
    .Call(`_GenePair_Patristic`, mcmc_samples, log_patristic_distances, x_pair, x_ind, z, spatial_dists, v, metrop_var_phi_trans, a_sigma2_epsilon_prior, b_sigma2_epsilon_prior, sigma2_regress_prior, a_sigma2_zeta_prior, b_sigma2_zeta_prior, a_tau2_prior, b_tau2_prior, a_phi_prior, b_phi_prior, sigma2_epsilon_init, beta_init, gamma_init, theta_init, sigma2_zeta_init, eta_init, tau2_init, phi_init)
}

SNP <- function(mcmc_samples, snp_distances, x_pair, x_ind, z, spatial_dists, v, metrop_var_phi_trans, a_r_prior = NULL, b_r_prior = NULL, sigma2_regress_prior = NULL, a_sigma2_zeta_prior = NULL, b_sigma2_zeta_prior = NULL, a_tau2_prior = NULL, b_tau2_prior = NULL, a_phi_prior = NULL, b_phi_prior = NULL, r_init = NULL, beta_init = NULL, gamma_init = NULL, theta_init = NULL, sigma2_zeta_init = NULL, eta_init = NULL, tau2_init = NULL, phi_init = NULL) {
    .Call(`_GenePair_SNP`, mcmc_samples, snp_distances, x_pair, x_ind, z, spatial_dists, v, metrop_var_phi_trans, a_r_prior, b_r_prior, sigma2_regress_prior, a_sigma2_zeta_prior, b_sigma2_zeta_prior, a_tau2_prior, b_tau2_prior, a_phi_prior, b_phi_prior, r_init, beta_init, gamma_init, theta_init, sigma2_zeta_init, eta_init, tau2_init, phi_init)
}

Sigma_update_tp <- function(m, Omega_Sigma_inv, nu_Sigma_inv, eta_z_g, eta_z_r, eta_w_g, eta_w_r, spatial_corr_inv) {
    .Call(`_GenePair_Sigma_update_tp`, m, Omega_Sigma_inv, nu_Sigma_inv, eta_z_g, eta_z_r, eta_w_g, eta_w_r, spatial_corr_inv)
}

Trans_Prob <- function(mcmc_samples, transmission_probabilities, x_pair, x_ind_g, x_ind_r, z_g, z_r, spatial_dists, v, metrop_var_phi_trans, metrop_var_nu_z, metrop_var_nu_w, sigma2_regress_prior = NULL, a_sigma2_nu_z_prior = NULL, b_sigma2_nu_z_prior = NULL, a_sigma2_zeta_z_g_prior = NULL, b_sigma2_zeta_z_g_prior = NULL, a_sigma2_zeta_z_r_prior = NULL, b_sigma2_zeta_z_r_prior = NULL, a_sigma2_epsilon_prior = NULL, b_sigma2_epsilon_prior = NULL, a_sigma2_nu_w_prior = NULL, b_sigma2_nu_w_prior = NULL, a_sigma2_zeta_w_g_prior = NULL, b_sigma2_zeta_w_g_prior = NULL, a_sigma2_zeta_w_r_prior = NULL, b_sigma2_zeta_w_r_prior = NULL, Omega_Sigma_inv_prior = NULL, nu_Sigma_inv_prior = NULL, a_phi_prior = NULL, b_phi_prior = NULL, beta_z_init = NULL, gamma_z_g_init = NULL, gamma_z_r_init = NULL, nu_z_init = NULL, sigma2_nu_z_init = NULL, theta_z_g_init = NULL, theta_z_r_init = NULL, sigma2_zeta_z_g_init = NULL, sigma2_zeta_z_r_init = NULL, eta_z_g_init = NULL, eta_z_r_init = NULL, sigma2_epsilon_init = NULL, beta_w_init = NULL, gamma_w_g_init = NULL, gamma_w_r_init = NULL, nu_w_init = NULL, sigma2_nu_w_init = NULL, theta_w_g_init = NULL, theta_w_r_init = NULL, sigma2_zeta_w_g_init = NULL, sigma2_zeta_w_r_init = NULL, eta_w_g_init = NULL, eta_w_r_init = NULL, Sigma_init = NULL, phi_init = NULL) {
    .Call(`_GenePair_Trans_Prob`, mcmc_samples, transmission_probabilities, x_pair, x_ind_g, x_ind_r, z_g, z_r, spatial_dists, v, metrop_var_phi_trans, metrop_var_nu_z, metrop_var_nu_w, sigma2_regress_prior, a_sigma2_nu_z_prior, b_sigma2_nu_z_prior, a_sigma2_zeta_z_g_prior, b_sigma2_zeta_z_g_prior, a_sigma2_zeta_z_r_prior, b_sigma2_zeta_z_r_prior, a_sigma2_epsilon_prior, b_sigma2_epsilon_prior, a_sigma2_nu_w_prior, b_sigma2_nu_w_prior, a_sigma2_zeta_w_g_prior, b_sigma2_zeta_w_g_prior, a_sigma2_zeta_w_r_prior, b_sigma2_zeta_w_r_prior, Omega_Sigma_inv_prior, nu_Sigma_inv_prior, a_phi_prior, b_phi_prior, beta_z_init, gamma_z_g_init, gamma_z_r_init, nu_z_init, sigma2_nu_z_init, theta_z_g_init, theta_z_r_init, sigma2_zeta_z_g_init, sigma2_zeta_z_r_init, eta_z_g_init, eta_z_r_init, sigma2_epsilon_init, beta_w_init, gamma_w_g_init, gamma_w_r_init, nu_w_init, sigma2_nu_w_init, theta_w_g_init, theta_w_r_init, sigma2_zeta_w_g_init, sigma2_zeta_w_r_init, eta_w_g_init, eta_w_r_init, Sigma_init, phi_init)
}

delta_update_pd <- function(y, x_trans, xtx, z, p_x, p_d, x_prior, sigma2_epsilon, theta_old) {
    .Call(`_GenePair_delta_update_pd`, y, x_trans, xtx, z, p_x, p_d, x_prior, sigma2_epsilon, theta_old)
}

delta_update_snp <- function(x, x_trans, z, p_x, p_d, x_prior, omega, lambda, omega_mat_delta, theta_old) {
    .Call(`_GenePair_delta_update_snp`, x, x_trans, z, p_x, p_d, x_prior, omega, lambda, omega_mat_delta, theta_old)
}

delta_w_update_tp <- function(x, x_trans, xtx, p_x, p_d, x_prior, w, sigma2_epsilon, beta_w_old, gamma_w_g_old, gamma_w_r_old, mu_w_old) {
    .Call(`_GenePair_delta_w_update_tp`, x, x_trans, xtx, p_x, p_d, x_prior, w, sigma2_epsilon, beta_w_old, gamma_w_g_old, gamma_w_r_old, mu_w_old)
}

delta_z_update_tp <- function(x, x_trans, p_x, p_d, x_prior, w_star, lambda, w_star_mat_delta, beta_z_old, gamma_z_g_old, gamma_z_r_old, mu_z_old) {
    .Call(`_GenePair_delta_z_update_tp`, x, x_trans, p_x, p_d, x_prior, w_star, lambda, w_star_mat_delta, beta_z_old, gamma_z_g_old, gamma_z_r_old, mu_z_old)
}

eta_update_pd <- function(v_trans, vtv, m, theta, sigma2_zeta, tau2_old, corr_inv) {
    .Call(`_GenePair_eta_update_pd`, v_trans, vtv, m, theta, sigma2_zeta, tau2_old, corr_inv)
}

eta_update_tp <- function(v_trans, vtv, m, theta, sigma2_zeta, eta_other, Sigma11, Sigma12, Sigma22_inv) {
    .Call(`_GenePair_eta_update_tp`, v_trans, vtv, m, theta, sigma2_zeta, eta_other, Sigma11, Sigma12, Sigma22_inv)
}

neg_two_loglike_update_clust <- function(y, x_pair, x_ind, z, beta, gamma, theta) {
    .Call(`_GenePair_neg_two_loglike_update_clust`, y, x_pair, x_ind, z, beta, gamma, theta)
}

neg_two_loglike_update_pd <- function(y, x_pair, x_ind, z, n_star, sigma2_epsilon, beta, gamma, theta) {
    .Call(`_GenePair_neg_two_loglike_update_pd`, y, x_pair, x_ind, z, n_star, sigma2_epsilon, beta, gamma, theta)
}

neg_two_loglike_update_snp <- function(y, x_pair, x_ind, z, n_star, r, beta, gamma, theta) {
    .Call(`_GenePair_neg_two_loglike_update_snp`, y, x_pair, x_ind, z, n_star, r, beta, gamma, theta)
}

neg_two_loglike_update_tp <- function(y, sigma2_epsilon, mu_z, mu_w) {
    .Call(`_GenePair_neg_two_loglike_update_tp`, y, sigma2_epsilon, mu_z, mu_w)
}

nu_w_update_tp <- function(y, n, index_nu, sigma2_epsilon, nu_w_old, sigma2_nu_w_old, mu_z_old, mu_w_old, metrop_var_nu_w, acctot_nu_w) {
    .Call(`_GenePair_nu_w_update_tp`, y, n, index_nu, sigma2_epsilon, nu_w_old, sigma2_nu_w_old, mu_z_old, mu_w_old, metrop_var_nu_w, acctot_nu_w)
}

nu_z_update_tp <- function(y, n, index_nu, nu_z_old, sigma2_nu_z_old, sigma2_epsilon_old, mu_z_old, mu_w_old, metrop_var_nu_z, acctot_nu_z) {
    .Call(`_GenePair_nu_z_update_tp`, y, n, index_nu, nu_z_old, sigma2_nu_z_old, sigma2_epsilon_old, mu_z_old, mu_w_old, metrop_var_nu_z, acctot_nu_z)
}

omega_update_clust <- function(y, x_pair, x_ind, z, n_star, n, p_x, p_d, beta_old, gamma_old, theta_old) {
    .Call(`_GenePair_omega_update_clust`, y, x_pair, x_ind, z, n_star, n, p_x, p_d, beta_old, gamma_old, theta_old)
}

omega_update_snp <- function(y, x_pair, x_ind, z, n_star, n, p_x, p_d, r, beta_old, gamma_old, theta_old) {
    .Call(`_GenePair_omega_update_snp`, y, x_pair, x_ind, z, n_star, n, p_x, p_d, r, beta_old, gamma_old, theta_old)
}

phi_update_pd <- function(spatial_dists, m, a_phi, b_phi, eta, tau2, phi_old, spatial_corr_info, metrop_var_phi_trans, acctot_phi_trans) {
    .Call(`_GenePair_phi_update_pd`, spatial_dists, m, a_phi, b_phi, eta, tau2, phi_old, spatial_corr_info, metrop_var_phi_trans, acctot_phi_trans)
}

phi_update_tp <- function(spatial_dists, m, a_phi, b_phi, eta_full, Sigma_inv, phi_old, spatial_corr_info, metrop_var_phi_trans, acctot_phi_trans) {
    .Call(`_GenePair_phi_update_tp`, spatial_dists, m, a_phi, b_phi, eta_full, Sigma_inv, phi_old, spatial_corr_info, metrop_var_phi_trans, acctot_phi_trans)
}

r_update_snp <- function(y, x_pair, x_ind, z, n_star, a_r, b_r, beta_old, gamma_old, theta_old) {
    .Call(`_GenePair_r_update_snp`, y, x_pair, x_ind, z, n_star, a_r, b_r, beta_old, gamma_old, theta_old)
}

rcpp_pgdraw <- function(b, c) {
    .Call(`_GenePair_rcpp_pgdraw`, b, c)
}

sigma2_epsilon_update_pd <- function(y, x_pair, x_ind, z, n_star, a_sigma2_epsilon, b_sigma2_epsilon, beta_old, gamma_old, theta_old) {
    .Call(`_GenePair_sigma2_epsilon_update_pd`, y, x_pair, x_ind, z, n_star, a_sigma2_epsilon, b_sigma2_epsilon, beta_old, gamma_old, theta_old)
}

sigma2_epsilon_update_tp <- function(n_star, a_sigma2_epsilon, b_sigma2_epsilon, w, mu_w) {
    .Call(`_GenePair_sigma2_epsilon_update_tp`, n_star, a_sigma2_epsilon, b_sigma2_epsilon, w, mu_w)
}

sigma2_nu_update <- function(n, a_sigma2_nu, b_sigma2_nu, nu) {
    .Call(`_GenePair_sigma2_nu_update`, n, a_sigma2_nu, b_sigma2_nu, nu)
}

sigma2_zeta_update <- function(v, n, a_sigma2_zeta, b_sigma2_zeta, theta, eta_old) {
    .Call(`_GenePair_sigma2_zeta_update`, v, n, a_sigma2_zeta, b_sigma2_zeta, theta, eta_old)
}

spatial_corr_fun <- function(m, spatial_dists, phi) {
    .Call(`_GenePair_spatial_corr_fun`, m, spatial_dists, phi)
}

tau2_update_pd <- function(m, a_tau2, b_tau2, eta, corr_inv) {
    .Call(`_GenePair_tau2_update_pd`, m, a_tau2, b_tau2, eta, corr_inv)
}

theta_update_pd <- function(y, x_pair, x_ind, z_trans, ztz, v, n, sigma2_epsilon, beta, gamma, sigma2_zeta_old, eta_old) {
    .Call(`_GenePair_theta_update_pd`, y, x_pair, x_ind, z_trans, ztz, v, n, sigma2_epsilon, beta, gamma, sigma2_zeta_old, eta_old)
}

theta_update_snp <- function(x_pair, x_ind, z, z_trans, v, n, omega, lambda, omega_mat_theta, beta, gamma, sigma2_zeta_old, eta_old) {
    .Call(`_GenePair_theta_update_snp`, x_pair, x_ind, z, z_trans, v, n, omega, lambda, omega_mat_theta, beta, gamma, sigma2_zeta_old, eta_old)
}

theta_w_update_tp <- function(z, z_trans, zgtzg, v, n, w, sigma2_epsilon, theta_w_old, sigma2_zeta_w_old, eta_w_old, mu_w_old) {
    .Call(`_GenePair_theta_w_update_tp`, z, z_trans, zgtzg, v, n, w, sigma2_epsilon, theta_w_old, sigma2_zeta_w_old, eta_w_old, mu_w_old)
}

theta_z_update_tp <- function(z, z_trans, v, n, w_star, lambda, w_star_mat_theta, theta_z_old, sigma2_zeta_z_old, eta_z_old, mu_z_old) {
    .Call(`_GenePair_theta_z_update_tp`, z, z_trans, v, n, w_star, lambda, w_star_mat_theta, theta_z_old, sigma2_zeta_z_old, eta_z_old, mu_z_old)
}

w_star_update_tp <- function(y, n_star, n, p_x, p_d, mu_z) {
    .Call(`_GenePair_w_star_update_tp`, y, n_star, n, p_x, p_d, mu_z)
}

w_update_tp <- function(y, n_star, sigma2_epsilon_old, mu_w) {
    .Call(`_GenePair_w_update_tp`, y, n_star, sigma2_epsilon_old, mu_w)
}

